### ISSUE TITLE
About saving output image with inference

### ISSUE THREAD

**Issue by efedoganay** [JialeCao001/D2Det-mmdet2.1#1]
Thank you,  I solved it.

**Comment by JialeCao001** [comment]
@efedoganay I update the code. Please refer the Demo part of Readme for saving images.

**Comment by efedoganay** [comment]
Hi thanks for the changes, do I need to recompile? Because after I changed the code manually I get:

Traceback (most recent call last):
  File "./demo/D2DET_demo.py", line 30, in <module>
    main()
  File "./demo/D2DET_demo.py", line 26, in main
    show_result_pyplot(args.img_file, result, model.CLASSES, out_file=args.out)
  File "/home/user/D2Det-mmdet2.1/demo/../mmdet/apis/inference.py", line 149, in show_result_pyplot
    img = model.show_result(img, result, score_thr=score_thr, show=False, out_file=out_file)
AttributeError: 'str' object has no attribute 'show_result

**Comment by JialeCao001** [comment]
I update D2DET_demo.py. Please change it.
