### ISSUE TITLE
Can you provide a 2.1 pre-trained model?

### ISSUE THREAD

**Issue by ma3252788** [JialeCao001/D2Det-mmdet2.1#2]
As stated in the following list, I used the pre-trained model of mm 1.1, but there are errors.
![image](https://user-images.githubusercontent.com/22229456/94148615-6c697480-fea9-11ea-826c-3ccf6294c4df.png)

![image](https://user-images.githubusercontent.com/22229456/94148746-9884f580-fea9-11ea-9f2c-f3ff490edc94.png)

**Comment by JialeCao001** [comment]
Hi. Currently I have no time to give the pre-trained model on mmdet2.1.

**Comment by ma3252788** [comment]
> Hi. Currently I have no time to give the pre-trained model on mmdet2.1.

Oh, that's a pity. Anyway, thank you very much for your reply.
